# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\natal\Downloads\Dat-Back\ui\pages\home.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import resource_rc

class home(object):
    def setupUi(self, home):
        home.setObjectName("home")
        home.resize(1024, 714)
        home.setStyleSheet("            QMainWindow {\n"
"                background-color: #545454; /* Цвет фона MainWindow */\n"
"                color: #FFFFFF; /* Белый цвет текста */\n"
"            }")
        self.centralwidget = QtWidgets.QWidget(home)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setGeometry(QtCore.QRect(0, 0, 991, 691))
        self.widget_3.setObjectName("widget_3")
        self.widget_2 = QtWidgets.QWidget(self.widget_3)
        self.widget_2.setGeometry(QtCore.QRect(30, 20, 941, 661))
        self.widget_2.setObjectName("widget_2")
        self.progressBar = QtWidgets.QProgressBar(self.widget_2)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(220, 600, 531, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("            QProgressBar {\n"
"                background-color: #0066cc; /* Цвет фона прогресс бара */\n"
"                text-align: center;\n"
"                border-width: 2px;\n"
"                border-radius: 15px;\n"
"                font: bold 14px;\n"
"                  padding: 6px;\n"
"                color: black;\n"
"                font: bold 16px;\n"
"            }\n"
"            QProgressBar::chunk {\n"
"                background-color: #61dafb; /* Цвет заливки прогресса */\n"
"                width: 20px; /* Ширина заливки прогресса (по умолчанию) */\n"
"            }")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.treeView = QtWidgets.QTreeView(self.widget_2)
        self.treeView.setGeometry(QtCore.QRect(50, 50, 871, 331))
        self.treeView.setStyleSheet("            QTreeView {\n"
"                background-color: #20232A;\n"
"                color: #61dafb; \n"
"                alternate-background-color: #374140;\n"
"                selection-background-color: #0066cc; \n"
"                 border-style: outset;\n"
"                border-width: 2px;\n"
"                border-radius: 5px;\n"
"                min-width: 10em;\n"
"                padding: 6px;\n"
"            }\n"
"            QTreeView::item {\n"
"                border-bottom: 1px solid #d1d1d1; /* Разделитель между элементами */\n"
"                padding: 5px; /* Отступы вокруг текста элемента */\n"
"            }\n"
"            QTreeView::item:selected {\n"
"                background-color: #0066cc; /* Цвет выделенного элемента */\n"
"                color: white; /* Цвет текста выделенного элемента */\n"
"            }\n"
"\n"
"            QSrollBar {\n"
"                background-color: #20232A;\n"
"                border-style: outset;\n"
"                border-width: 2px;\n"
"                border-radius: 5px;\n"
"                font: bold 14px;\n"
"                min-width: 10em;\n"
"                padding: 6px;\n"
"            \n"
"            }\n"
"\n"
"")
        self.treeView.setObjectName("treeView")
        self.treeView.header().setCascadingSectionResizes(True)
        self.frame = QtWidgets.QFrame(self.widget_2)
        self.frame.setGeometry(QtCore.QRect(50, 400, 881, 51))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn_increment = QtWidgets.QPushButton(self.frame)
        self.btn_increment.setGeometry(QtCore.QRect(350, 0, 191, 51))
        self.btn_increment.setStyleSheet("            QWidget {\n"
"                background-color: #20232A;\n"
"                color: #61dafb;\n"
"            }\n"
"            QPushButton {\n"
"                border-style: outset;\n"
"                border-width: 2px;\n"
"                border-radius: 10px;\n"
"                font: bold 14px;\n"
"                min-width: 10em;\n"
"                padding: 6px;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #0066cc;\n"
"            }\n"
"            QLabel {\n"
"                color: #61dafb;\n"
"                font: bold 16px;\n"
"            }")
        self.btn_increment.setObjectName("btn_increment")
        self.btn_copy = QtWidgets.QPushButton(self.frame)
        self.btn_copy.setGeometry(QtCore.QRect(120, 0, 191, 51))
        self.btn_copy.setStyleSheet("            QWidget {\n"
"                background-color: #20232A;\n"
"                color: #61dafb;\n"
"            }\n"
"            QPushButton {\n"
"                border-style: outset;\n"
"                border-width: 2px;\n"
"                border-radius: 10px;\n"
"                font: bold 14px;\n"
"                min-width: 10em;\n"
"                padding: 6px;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #0066cc;\n"
"            }\n"
"            QLabel {\n"
"                color: #61dafb;\n"
"                font: bold 16px;\n"
"            }")
        self.btn_copy.setObjectName("btn_copy")
        self.btn_different = QtWidgets.QPushButton(self.frame)
        self.btn_different.setGeometry(QtCore.QRect(590, 0, 221, 51))
        self.btn_different.setStyleSheet("            QWidget {\n"
"                background-color: #20232A;\n"
"                color: #61dafb;\n"
"            }\n"
"            QPushButton {\n"
"                border-style: outset;\n"
"                border-width: 2px;\n"
"                border-radius: 10px;\n"
"                font: bold 14px;\n"
"                min-width: 10em;\n"
"                padding: 6px;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #0066cc;\n"
"            }\n"
"            QLabel {\n"
"                color: #61dafb;\n"
"                font: bold 16px;\n"
"            }")
        self.btn_different.setObjectName("btn_different")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.widget_2)
        self.plainTextEdit.setGeometry(QtCore.QRect(50, 470, 871, 121))
        self.plainTextEdit.setStyleSheet("QPlainTextEdit \n"
"{                  border-style: outset;\n"
"                border-width: 2px;\n"
"                border-radius: 5px;\n"
"                font: bold 14px;\n"
"                min-width: 10em;\n"
"                padding: 6px;\n"
"}\n"
"\n"
"            QWidget {\n"
"                background-color: #20232A;\n"
"                color: #61dafb;\n"
"            }")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.frame_2 = QtWidgets.QFrame(self.widget_2)
        self.frame_2.setGeometry(QtCore.QRect(50, 10, 561, 31))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_size_2 = QtWidgets.QLabel(self.frame_2)
        self.label_size_2.setGeometry(QtCore.QRect(-10, -10, 271, 41))
        self.label_size_2.setStyleSheet("            QWidget {\n"
"                color: #61dafb;\n"
"            }\n"
"            QLabel {\n"
"                border-width: 2px;\n"
"                border-radius: 10px;\n"
"                font: bold 14px;\n"
"                min-width: 10em;\n"
"                padding: 6px;\n"
"                color: #61dafb;\n"
"                font: bold 16px;\n"
"            }")
        self.label_size_2.setObjectName("label_size_2")
        self.label_size = QtWidgets.QLabel(self.frame_2)
        self.label_size.setGeometry(QtCore.QRect(250, -10, 202, 41))
        self.label_size.setStyleSheet("            QWidget {\n"
"                color: #61dafb;\n"
"            }\n"
"            QLabel {\n"
"                border-width: 2px;\n"
"                border-radius: 10px;\n"
"                font: bold 14px;\n"
"                min-width: 10em;\n"
"                padding: 6px;\n"
"                color: #61dafb;\n"
"                font: bold 16px;\n"
"            }")
        self.label_size.setText("")
        self.label_size.setObjectName("label_size")
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        home.setCentralWidget(self.centralwidget)

        self.retranslateUi(home)
        QtCore.QMetaObject.connectSlotsByName(home)

    def retranslateUi(self, home):
        _translate = QtCore.QCoreApplication.translate
        home.setWindowTitle(_translate("home", "MainWindow"))
        self.btn_increment.setText(_translate("home", "Инкрементная копия"))
        self.btn_copy.setText(_translate("home", "Полная копия"))
        self.btn_different.setText(_translate("home", "Диференциальная копия"))
        self.label_size_2.setText(_translate("home", "Размер выбранных данных:"))

